### ISSUE TITLE
Determining the most confident cycles

### ISSUE THREAD

**Issue by Vini2** [austenb28/CycFlowDec#2]
Hello!

Are there any statistics recorded regarding how confident the decomposed cycles are? Like a probability value?

Thank you!

Best regards,
Vijini

**Comment by austenb28** [comment]
Hi Vijini,

The decomposition algorithm is completely deterministic, so there actually is no statistical error.  However, there is systematic error, which could be estimated for each cycle.  There are a number of ways to estimate systematic error for these types of algorithms via asymptotic analysis, but that's probably too complicated to get into here.  I think the most practical way to get an estimate for the systematic error of each cycle is probably to just measure the error with respect to a previous step, and use this as an approximate upper bound for the estimated error at the final step.  Assuming the total number of steps was 1000, programmatically this could look something like

1. Run decomposition for 700 steps
2. Store the scaled cycles with copy.deepcopy() in c_1
3. Continue decomposition for 300 steps
4. Store scaled cycles as c_2

The estimated absolute, systematic error for cycle j is just |c_2[j] - c_1[j]|.  For this example I chose c_1 to be sampled at 70% of the total cycles, but you could plot the error vs. that percentage to use a more informed percentage.  Ideally you choose the highest percentage that is not so high that it's deviation from c_2 is significantly affected by the fact that c_2 does not contain true flow values.

Note that a measure of the systematic error for the total network is provided with CycFlowDec in the form of the mean relative error (MRE) of all edges in the network.  This systematic error is easy to directly assess, as the true flow value of each edge is already known.

Best,
Austen
